#!/usr/bin/env python
#  -*- coding: utf-8 -*-
# *****************************************************************************
# ufit, a universal scattering fitting suite
#
# Copyright (c) 2014, Georg Brandl.  All rights reserved.
# Licensed under a 2-clause BSD license, see LICENSE.
# *****************************************************************************

import sys
import time
from os import path

t0 = time.time()

import sip
sip.setapi('QString', 2)
sip.setapi('QVariant', 2)

from PyQt4.QtCore import Qt
from PyQt4.QtGui import QApplication, QSplashScreen, QPixmap

import matplotlib
matplotlib.use('Qt4Agg')

import ufit.guiresource

app = QApplication([])
app.setOrganizationName('ufit')
app.setApplicationName('gui')

pixmap = QPixmap(':/splash.png')
splash = QSplashScreen(pixmap, Qt.WindowStaysOnTopHint)
splash.show()
time.sleep(0.1)
app.processEvents()

from ufit.gui.main import UFitMain

t1 = time.time()
print 'import finished (%.3f s), starting up app...' % (t1-t0)

mainwindow = UFitMain()
args = sys.argv[1:]
if len(args) == 1:
    datafile = path.abspath(args[0])
    if datafile.endswith('.ufit'):
        try:
            mainwindow.filename = datafile
            mainwindow.load_session(datafile)
        except Exception, err:
            QMessageBox.warning(mainwindow,
                                'Error', 'Loading failed: %s' % err)
            mainwindow.filename = None
    else:
        mainwindow.dloader.set_template(datafile)

t2 = time.time()
print 'loading finished (%.3f s), main window showing...' % (t2-t1)
mainwindow.show()
splash.deleteLater()
app.exec_()
