#!/usr/bin/env python
#  -*- coding: utf-8 -*-
# *****************************************************************************
# ufit, a universal scattering fitting suite
#
# Copyright (c) 2013, Georg Brandl.  All rights reserved.
# Licensed under a 2-clause BSD license, see LICENSE.
# *****************************************************************************

import sys

import time
t0 = time.time()

import matplotlib
matplotlib.use('Qt4Agg')

from ufit.gui.main import main

sys.exit(main(sys.argv[1:], t0))
